# TYPES:
# none - No style conversion
# shakespearean - People talk like Shakespeare
# royal - People talk like the Queen
# scholar - People talk in a scholarly manner
# complex_writer - People use very complex words and structures
# poet - People talk like a poet
# rhyming - People talk in continuous rhymes
# yoda - People talk like Yoda
# pirate - People talk like a pirate
# western - People talk like Old West cowboys
# valley - People talk like people from the valley
# baby - People talk like a baby
# child - People talk like a child
# goth - People talk in a goth style
# depressing - People talk in a depressing tone
# very_sad - People talk in a very sad manner
# stutter - People talk with a stutter
# robotic - People talk like a robot
# computer - People talk in a computer-like manner
# nonsense - People talk in a nonsensical way
# newscaster - People talk like a news reporter
# otherworldly - People talk in an otherworldly or mystical manner
# trump - People talk like Trump
# andrew_tate - People talk in an obnoxious Andrew Tate-like manner
# eminem - People talk like Eminem
# snoop_dogg - People talk like Snoop Dogg
# professional - Converts text to a professional tone
# grammar - Ensures proper grammar usage
# concise - Makes the text more concise and to the point
# simpleton - Simplifies the text to very basic words and structure
# abbreviated - Converts the text to abbreviated, texting-style language
# sarcastic - Converts the text to a sarcastic tone
# no_swearing - Removes any swearing from the text
# custom - You can define your own prompt
style: SHAKESPEAREAN

# If you used the CUSTOM conversion, you can define your own prompt here
prompt: "Convert text to shakespearean"

# MODEL:
# gpt-4o-mini - (RECOMMENDED) a small, fast, and cheaper model produced by OpenAI
# gpt-4o - gpt-4o, a large, powerful, and expensive model produced by OpenAI
# custom - You can define your own model
model: gpt-4o-mini

# This is the authorisation key for the API
# This could be an API key, a username and password, or any other form of authorisation
# An API key might look like this: "#sk-...jGQA" for OpenAI
auth: "YOUR_AUTHORISATION_KEY"

# If you used the CUSTOM model, you can define your own model here
# The route will need to accept a POST request with the following JSON body:
# {
#   "prompt": "The system to convert the text to (e.g. shakespearean)",
#   "message": "The text to convert"
# }
# And return a JSON object with the following structure:
# {
#   "message": "The converted text"
# }
# The model_url should be the URL of the route
# For example, "https://api.openai.com/v1/chat/completions" for OpenAI
model_url: "YOUR_MODEL_URL"