name: AShakespeareanChat
version: '1.0-SNAPSHOT'
main: me.coriew.ashakespeareanchat.AShakespeareanChat
api-version: '1.21'
author: CorieW
description: A plugin that converts chat messages to different styles of English

# Commands
commands:
  asccurrent:
    description: Check the current style of chat
    usage: /asccurrent
    permission: asc.current
  ascchange:
    description: Change the style of chat
    usage: /ascchange <style>
    permission: asc.change
  ascconfig:
    description: View the plugin configuration
    usage: /ascconfig
    permission: asc.config
  ascreload:
    description: Reload the plugin
    usage: /ascreload
    permission: asc.reload